# Generated by Django 4.2.15 on 2024-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída')], default='pendente', max_length=50),
        ),
    ]

